In [81]:
import numpy as np

In [82]:
floating_point = 6  # Computation precision is 6 digits

In [86]:
from itertools import chain, combinations

def powerset(iterable):
  """
  Source: https://stackoverflow.com/questions/1482308/how-to-get-all-subsets-of-a-set-powerset
  """
  s = list(iterable)
  return chain.from_iterable(combinations(s, r) for r in range(len(s)+1))

In [87]:
def is_TUM(mat) -> (bool, str):
  """
  return True if mat is TUM (Totally Unimodular Matrix), else return False and the reason.
  The result is achieved by "TUM definition", which means with matrix NXN 
  the algorithm do iterations on on all subsets of n rows and columns and calculate its det.
  In other words: runtime complexity is: O(num subsets) = O(N!)
  """
  rows_power_set = list(powerset(range(mat.shape[0])))
  cols_power_set = list(powerset(range(mat.shape[1])))

  for r_set in rows_power_set:
    # print(r_set)
    if len(r_set) <= 0:
      # print("do continue on rows")
      continue

    for c_set in cols_power_set:
      if len(c_set) <= 0:
        # print("do continue on cols")
        continue

      rs = list(r_set)
      cs = list(c_set)

      if len(rs) != len(cs):
        # print(f"don't calc MUT of: rl: {rs}, rc: {cs}")
        continue

      # print(f"rl: {rs}, rc: {cs}")

      # Source: https://numpy.org/doc/stable/reference/generated/numpy.ix_.html
      ixgrid = np.ix_(rs, cs)
      sub_mat = mat[ixgrid]
      # print(sub_mat)

      det = np.around(np.linalg.det(sub_mat), floating_point)
      
      if not(det == 0. or abs(det) == 1.):
        # if det is not 0, 1 or -1, the matrix is not TUM
        # print(f"matrix is not TUM, because the det of of sub-matrix:\n {sub_mat}\n is equal {det}")
        return (False, f"matrix is not TUM, because the det of of sub-matrix:\n {sub_mat}\n is equal {det}\nrows:{rs}, cols:{cs}")

  return (True, "")


In [88]:
# a = np.arange(10).reshape(2, 5)

In [89]:
mat = np.asarray([
                  [-1, 0, 0, -1, -1, 0, 0],
                  [-1, -1, -1, 0, 0, 0, 0],
                  [0, -1, 0, 0, 0, -1, -1],
                  [-1, 0, -1, 0, 0, 0, -1],
                  [0, -1, -1, 0, 0, -1, -1],

                  [1, 0, 0, 0, 0, 0, 0],
                  [0, 1, 0, 0, 0, 0, 0],
                  [0, 0, 1, 0, 0, 0, 0],
                  [0, 0, 0, 1, 0, 0, 0],
                  [0, 0, 0, 0, 1, 0, 0],
                  [0, 0, 0, 0, 0, 1, 0],
                  [0, 0, 0, 0, 0, 0, 1]
])

In [90]:
is_tum, reason = is_TUM(mat)
print(reason)

matrix is not TUM, because the det of of sub-matrix:
 [[-1 -1  0]
 [ 0 -1 -1]
 [-1  0 -1]]
 is equal -2.0
rows:[1, 2, 3], cols:[0, 1, 6]
